### ISSUE TITLE
procs is not defined with version 0.3.4

### ISSUE THREAD

**Issue by vkadam** [cri5ti/grunt-shell-spawn#36]
Getting following error with latest version (v0.3.4)
```code
/var/lib/jenkins/jobs/test-job/node_modules/grunt-shell-spawn/tasks/shell.js:152
        _.forEach(procs, function (proc, key, collection) {
                  ^
ReferenceError: procs is not defined
    at process.<anonymous> (/var/lib/jenkins/jobs/test-job/node_modules/grunt-shell-spawn/tasks/shell.js:152:19)
    at process.EventEmitter.emit (events.js:107:17)
    at process.exit (node.js:597:17)
    at tryToExit (/var/lib/jenkins/jobs/test-job/node_modules/grunt/node_modules/exit/lib/exit.js:17:15)
    at Object.exit (/var/lib/jenkins/jobs/test-job/node_modules/grunt/node_modules/exit/lib/exit.js:34:3)
    at Object.task.options.done (/var/lib/jenkins/jobs/test-job/node_modules/grunt/lib/grunt.js:154:14)
    at Task.<anonymous> (/var/lib/jenkins/jobs/test-job/node_modules/grunt/lib/util/task.js:280:25)
    at /var/lib/jenkins/jobs/test-job/node_modules/grunt/lib/util/task.js:227:11
    at process._tickCallback (node.js:343:11)
```code

**Comment by bittorture** [comment]
Just pushed a fix.  Sorry I don't have commit access to the npm repo to push fix there. @dandv?

**Comment by prassh123** [comment]
+1 

ReferenceError: procs is not defined
  at process.<anonymous> 
  at process.emit (events.js:117:20)
  at process.exit (node.js:711:17)

**Comment by dandv** [comment]
`npm publish`ed. Thanks @bittorture.
